### ISSUE TITLE
help with transform name

### ISSUE THREAD

**Issue by Sirfrancis17** [Webreaper/SonarrAutoImport#1]
hi
"There is an optional 4th parameter, which is the path to a 'transforms' file. This is a text file whose contents will be of the form"
where create this file.txt ?
example?
SonarrAutoImport "/volume1/video/Downloads" 12345678901234567890123456 http://192.168.1.30:8989  file.txt???
thanks

**Comment by Webreaper** [comment]
The text file needs to be in the same folder as the executable. There's several examples in the readme.

**Comment by Sirfrancis17** [comment]
thanks a lot
