### ISSUE TITLE
Idiot Guide to Install....

### ISSUE THREAD

**Issue by LordChoakem** [Webreaper/SonarrAutoImport#12]
This looks like a super handy script but I can t figure out how to install it...

Any chance of a quick install guide?

Looking forward to testing this.

**Comment by Webreaper** [comment]
It's just a command-line util with a single binary. There's no installation.

1. Download the right version for your OS from the releases page
2. Create the json settings file (there's an example linked from the readme)
3. Run it
4. Maybe set it up to run regularly via the scheduler of your choice.
