### ISSUE TITLE
Upgrade to Sonarr v4

### ISSUE THREAD

**Issue by laryan61** [Webreaper/SonarrAutoImport#15]
I think this is just what I might need for a recently upgraded Sonarr v4 installation.

Edit. Disregard. I didn't notice this was for a Windows installation, My installation runs on Ubuntu. I would need something like a python script.

**Comment by Webreaper** [comment]
It's not only for Windows. In fact, it wasn't written for Windows (I don't have any Windows boxes in my house). I run it on a Synology NAS, which is a linux OS. SonarrAutoImport can run on Mac, Windows and Linux. 

Also, I've been using it fine with Sonarr v4 for about a year, so I'll close this issue.
