### ISSUE TITLE
SonarrAutoImport: command not found

### ISSUE THREAD

**Issue by Sirfrancis17** [Webreaper/SonarrAutoImport#2]
plex@ubuntu1804:/datos/script$ SonarrAutoImport "/home/gdrive/Procesado/" API http://localhost:8989/ -dry-run
SonarrAutoImport: command not found
plex@ubuntu1804:/datos/script$
What could be the mistake?

**Comment by Sirfrancis17** [comment]
hi 
the command its work but it always says could not find a part of the path
it's necessary execute the program where is the sonarr server?
change the 4th  variable is for this?
folder is in      root/datos/downloads
when i execute    SonarrAutoImport "/datos/download" xxxxx  http://xxxxx.com:8989/ -dry-run dont find the folder

**Comment by Sirfrancis17** [comment]
finally i execute in server but shows this error 
![image](https://user-images.githubusercontent.com/44566906/68995457-6de00e80-088e-11ea-8ae4-ac5df7bf950b.png)

**Comment by Sirfrancis17** [comment]
with -dry-run its ok
![image](https://user-images.githubusercontent.com/44566906/68995468-9b2cbc80-088e-11ea-991e-3fc13b783d8f.png)

**Comment by don199** [comment]
mine does the same thing.  If I add an additional path at the end of the command it doesn't throw any errors but in both cases, nothing actually happens.  No files are imported.
![sonarr screenshot](https://user-images.githubusercontent.com/28150180/70062539-34a8dd80-15b4-11ea-878d-c174ba19d0e7.jpg)

**Comment by Webreaper** [comment]
Looks like the readme needs updating. 
4th argument is the mapping folder - the remote folder path. 5th argument is the path to the transform file. So I have:

`./SonarrAutoImport "/volume1/video/Downloads" apikey12345apikey12345 http://192.168.1.30:8989 /downloads/ /var/services/homes/admin/SonarrImport/SonarrTransforms.txt > sonarrimport.log`

The /downloads/ should be the same as your base folder to process, unless you have a mapping folder set up in sonarr.

**Comment by don199** [comment]
I'm not sure what I'm doing wrong here.  I'm running Sonarr on a Windows 10 machine. I don't have any remote path mappings.  I download everything manually and then move the files to my drone factory folder where Sonarr scans and moves the files to other shared drives on my LAN.
