### ISSUE TITLE
[Feature Request] Auto Check At Specified Interval For Files

### ISSUE THREAD

**Issue by 0x0D15** [Webreaper/SonarrAutoImport#3]
First off thanks for this fantastic tool its literally the only thing that I have found that actually replaces drone factory properly. Would you consider implementing the scan specified directory every X minutes and import feature that drone factory had? I always found it easier to use that feature instead of setting up a cronjob and it would be great you are able to.

**Comment by Webreaper** [comment]
I've thought about doing this, but it seems unnecessary for me to go to the trouble of writing a scheduler to run the scan on-demand when Cron (and all of the other schedulers on OSX, Linux and Windows) do such a great job and are so simple to use. It's better to keep the tool simple and focus on the features it provides, than re-invent the scheduling wheel.
