### ISSUE TITLE
Add delayed processing

### ISSUE THREAD

**Issue by jortan** [Webreaper/SonarrAutoImport#7]
Thanks for this project, it certainly fills a gap after "drone factory" functionality was deprecated.

Can I suggest a feature to allow delayed processing of files.  SonarrAutoImport would enumerate files and then delay processing for the nominated time.   This would prevent issues where a file is still being created in the location where it is to be moved from.  (I suspect this is one of the reasons why the drone factory was removed in the first place)

**Comment by Webreaper** [comment]
Funnily enough, I'd added that feature in my local build - to skip any .partial file, and also ignore any file whose last-write time is within the last 5 mins. I've just not built a release. I'll try and do a release.

**Comment by Webreaper** [comment]
https://github.com/Webreaper/SonarrAutoImport/releases/tag/1.3

**Comment by jortan** [comment]
Sorry to be a pain, grabbed this: https://github.com/Webreaper/SonarrAutoImport/releases/download/1.3/SonarrAutoImport-linux-x64.zip

unzipped, diff says SonarrAutoImport is the same file I already had, datestamp is same, May 18

SonarrAutoImport --version returns:

`SonarrAutoImport 1.0.0`

**Comment by Webreaper** [comment]
Oops. Sorry, I'll try and do a new build/release this evening.

**Comment by Webreaper** [comment]
Have re-added the binaries to the release - can you try now?

**Comment by jortan** [comment]
Perfect, working as expected - thanks!
