### ISSUE TITLE
Running on Synology NAS as scheduled task.

### ISSUE THREAD

**Issue by GenesisAdam** [Webreaper/SonarrAutoImport#8]
How do I run this as a scheduled task on Synology NAS?

**Comment by Webreaper** [comment]
Copy the binary somewhere on your Syno, and create the config file in the same folder. I put it into ~/SonarrImport
Then set up a scheduled task to run it:
https://kb.synology.com/tr-tr/DSM/help/DSM/AdminCenter/system_taskscheduler?version=6

**Comment by GenesisAdam** [comment]
@Webreaper Thanks for your quick response. That's what I did using this:
exec /volume1/apps/SonarrAutoImport, I have also tried it wihout the exec,
in the scheduled task script on synology nas, but does not appear to work when I run it manually to test.
Many thanks.

**Comment by Webreaper** [comment]
You don't need `exec`. It's a binary already. 
Do this:
1. Copy the exe to a folder in your home directory (e.g., in File Station, create a folder `/homes/admin/SonarrImport` (I'm assuming your username is `admin`).
2. `ssh` onto the NAS, and `cd` to the folder you created
3. Run the command `./SonarrAutoImport` which should execute it. If you haven't already created the settings you'll see an error. 
4. To run it from the scheduled tasks thing, create a file called `sonarrimport.sh`, and put one line in it, with `./SonarrAutoImport`. Save that, and reference that in the scheduled task.

If you don't get it to work with these steps, I suggest asking for help with your linux usage (e.g., http://reddit.com/r/synology). I can't really provide DSM/linux tutorials. :)

One final thing - make sure your Synology is an x64 Intel one. This app won't run on an ARM synology.

**Comment by GenesisAdam** [comment]
@Webreaper It's working now from the ssh. I am sure it will work with the scheduler as well. I am a DBA, not a Linux programmer. Really helpful with my iPlayer downloads. Many thanks for your help.

**Comment by Webreaper** [comment]
Cool! Glad you got it sorted.

I was a Windows Dev until about 5 years ago, but learnt Linux. You should totally do that. DSM is a perfect place for it!
